spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anupam-2020/ecommerce-config-server.git
          username: Anupam-2020
          password:
          default-label: master
server:
    port: 8888

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka