// Wrapper around primitive types is wrapper class...

public class wrappper {
    public static void main(String[] args) {
        int num = 8; // primitive int...
        Integer num1 = 8; // Wrapper Integer...

        Integer num2 = num; // auto-boxing -> here, prmitive type is stored in wrapper class..
        int num3 = num2; // auto-unboxing -> here wrapper class object is stored in primitive type...
    }
}
