spring.application.name=userService

server.servlet.context-path=/api/v1/users
server.port=9020

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

jwt.secretKey=adhviodj32bioryfejcbjkasbjkasGUGHLKBkblkhdsivoKLHDSIV