spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=anupamanand
spring.datasource.password=gfe3sjb2108#_4*2

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#security config
#spring.security.user.name=anupam
#spring.security.user.password=pass

jwt.secretKey=sakchioefgeqfyeq8iujkhbrb24fnvdniowybfjkzevklhewoif3greukilo8pf