spring.application.name=studentManagementJpa

spring.datasource.url=jdbc:mysql://localhost:3306/enrollment_db
spring.datasource.username=root
spring.datasource.password=gfe3sjb2108#_4*2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect