spring.application.name=springSecurity

#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/spring-securityDB?useSSL=false
spring.datasource.username=root
spring.datasource.password=gfe3sjb2108#_4*2

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security configs
#spring.security.user.name=anupam
#spring.security.user.password=anand

jwt.secretKey=jdkvguo8e6f9q78tugO4qbrj^&*%&q3hqnmf,ewbvjkhioeqy784678faytcs8tfqYI