spring.application.name=springSecurity

#DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDatabase?useSSL=false
spring.datasource.username=root
spring.datasource.password=gfe3sjb2108#_4*2

# here we can set create/update/none/validate
spring.jpa.hibernate.ddl-auto=create

#Format the SQL statements for better readability in the logs.
#spring.jpa.properties.hibernate.format_sql=true

#Specify the Hibernate dialect to use for MySQL. This helps Hibernate generate SQL optimized for MySQL databases.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# below properties are used to initialize the database with data.sql file, and defer the initialization until the datasource is ready
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql